# Tablas y figuras

## Características básicas de una tabla/figura

- La información de tablas y figuras no debe ser redundante.
- Las figuras deben ser explanatorias en interpretables por sí solas
- Cuida aspectos que puedan llevar a malas interpretaciones (e.g., escala de los ejes)
- Invierte tiempo en preparar figuras bonitas.
  - Figuras con excel: [Ejemplo feo](https://link.springer.com/article/10.1007/s11192-018-2738-2), [ejemplo bonito](https://www.sciencedirect.com/science/article/pii/S1751157713000060).
  - Figuras con R: [Ejemplo feo](https://doi.org/10.1371/journal.pone.0068258.s001), [ejemplo bonito](https://doi.org/10.7717/peerj.9410/fig-4)

## ¿Dónde y cuántas figuras incluir? 

Utiliza las figuras como un recurso discursivo para:

- Sintetizar y resumir procesos. [Ejemplo](https://doi.org/10.7717/peerj.9410/fig-1)
- Facilitar la interpretación de resultados. [Ejemplo](https://asistdl.onlinelibrary.wiley.com/doi/full/10.1002/asi.22837)
- Mostrar ejemplos a tipo ilustrativo. [Ejemplo](https://link.springer.com/content/pdf/10.1007/s11192-013-1157-7.pdf)

## Cuestiones de estética

- Sé consistente a lo largo del paper - [Ejemplo](https://doi.org/10.31235/osf.io/ve7d3)
- Utiliza paletas de colores - Explora [esta web](https://www.color-hex.com/color-palettes/)
- Baraja opciones creativas para visualizar tus datos - [The Chartmaker Directory](http://chartmaker.visualisingdata.com/)
- Si quieres ponerte exquisito utiliza una paleta para los daltónicos - [La paleta Viridis](https://cran.r-project.org/web/packages/viridis/vignettes/intro-to-viridis.html)

Si te interesa el tema de la visualización de datos te recomiendo [este libro online de Claus O. Wilke](https://clauswilke.com/dataviz/).

## Software para crear figuras

Listado no exhaustivo:

- Excel
- [RStudio](https://www.rstudio.com/) (paquetes [ggplot2](https://ggplot2.tidyverse.org/) y [ggpubr](http://sthda.com/english/articles/24-ggpubr-publication-ready-plots/))
- [Vosviewer](https://www.vosviewer.com/)
- [Tableau](https://www.tableau.com/)
- [Inkscape](https://inkscape.org/)
- [Gephi](https://gephi.org/)
